featured_tags:
  type: list
  list_type: tag
  default: "featured"
layout:
  type: enum
  default: "cards"
  choices:
    - cards
    - list
    - full-bleed
    - none
max_topic_count: 4
randomize_topics: true
show_with_img_only: false
show_on_mobile: true
show_on:
  default: homepage
  type: enum
  choices:
    - everywhere
    - homepage
    - top-menu
    - latest
    - categories
    - top
    - custom
plugin_outlet: "above-main-container"
desktop_card_width:
  type: string
  default: ""
  description: "Width of each card on desktop (e.g., 300px, 20em, 25rem, 30%, 30vw). Leave empty to use default responsive widths."
mobile_card_width:
  type: string
  default: ""
  description: "Width of each card on mobile (e.g., 300px, 20em, 25rem, 85%, 85vw). Leave empty to use default responsive width (85%)."
